//
// AddIntroOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddIntroOptions: Sendable, Codable, JSONEncodable, Hashable {

    public var file: URL?

    public init(file: URL? = nil) {
        self.file = file
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(file, forKey: .file)
    }
}

