//
// AddPlaylist200ResponseVideoPlaylist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddPlaylist200ResponseVideoPlaylist: Sendable, Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let uuidRule = StringRule(minLength: 36, maxLength: 36, pattern: "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/")
    public var id: Int?
    public var uuid: UUID?
    /** translation of a uuid v4 with a bigger alphabet to have a shorter uuid */
    public var shortUUID: String?

    public init(id: Int? = nil, uuid: UUID? = nil, shortUUID: String? = nil) {
        self.id = id
        self.uuid = uuid
        self.shortUUID = shortUUID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
        case shortUUID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(shortUUID, forKey: .shortUUID)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AddPlaylist200ResponseVideoPlaylist: Identifiable {}
