//
// AddVideoPlaylistVideoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoPlaylistVideoRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var videoId: AddVideoPlaylistVideoRequestVideoId
    /** Start the video at this specific timestamp */
    public var startTimestamp: Int?
    /** Stop the video at this specific timestamp */
    public var stopTimestamp: Int?

    public init(videoId: AddVideoPlaylistVideoRequestVideoId, startTimestamp: Int? = nil, stopTimestamp: Int? = nil) {
        self.videoId = videoId
        self.startTimestamp = startTimestamp
        self.stopTimestamp = stopTimestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videoId
        case startTimestamp
        case stopTimestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(videoId, forKey: .videoId)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(stopTimestamp, forKey: .stopTimestamp)
    }
}

