//
// AddVideoChannel200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoChannel200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var videoChannel: ApiV1AbusesPost200ResponseAbuse?

    public init(videoChannel: ApiV1AbusesPost200ResponseAbuse? = nil) {
        self.videoChannel = videoChannel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videoChannel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videoChannel, forKey: .videoChannel)
    }
}

