//
// AddVideoPlaylistVideo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoPlaylistVideo200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var videoPlaylistElement: AddVideoPlaylistVideo200ResponseVideoPlaylistElement?

    public init(videoPlaylistElement: AddVideoPlaylistVideo200ResponseVideoPlaylistElement? = nil) {
        self.videoPlaylistElement = videoPlaylistElement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videoPlaylistElement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videoPlaylistElement, forKey: .videoPlaylistElement)
    }
}

