//
// ApiV1VideosOwnershipIdAcceptPostIdParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiV1VideosOwnershipIdAcceptPostIdParameter: Sendable, Codable, JSONEncodable, Hashable {
    case typeInt(Int)
    case typeString(String)
    case typeUUID(UUID)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeInt(let value):
            try container.encode(value)
        case .typeString(let value):
            try container.encode(value)
        case .typeUUID(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Int.self) {
            self = .typeInt(value)
        } else if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else if let value = try? container.decode(UUID.self) {
            self = .typeUUID(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ApiV1VideosOwnershipIdAcceptPostIdParameter"))
        }
    }
}

