//
// ApiV1RunnersJobsRequestPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsRequestPostRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var runnerToken: String
    /** Filter jobs depending on their types */
    public var jobTypes: [String]?

    public init(runnerToken: String, jobTypes: [String]? = nil) {
        self.runnerToken = runnerToken
        self.jobTypes = jobTypes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case runnerToken
        case jobTypes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(runnerToken, forKey: .runnerToken)
        try container.encodeIfPresent(jobTypes, forKey: .jobTypes)
    }
}

