//
// ApiV1WatchedWordsAccountsAccountNameListsPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1WatchedWordsAccountsAccountNameListsPost200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var watchedWordsList: RequestUserExport200ResponseExport?

    public init(watchedWordsList: RequestUserExport200ResponseExport? = nil) {
        self.watchedWordsList = watchedWordsList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case watchedWordsList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(watchedWordsList, forKey: .watchedWordsList)
    }
}

