//
// ApiV1AbusesAbuseIdPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1AbusesAbuseIdPutRequest: Sendable, Codable, JSONEncodable, Hashable {

    public static let moderationCommentRule = StringRule(minLength: 2, maxLength: 3000, pattern: nil)
    public var state: AbuseStateSet?
    /** Update the report comment visible only to the moderation team */
    public var moderationComment: String?

    public init(state: AbuseStateSet? = nil, moderationComment: String? = nil) {
        self.state = state
        self.moderationComment = moderationComment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case state
        case moderationComment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(moderationComment, forKey: .moderationComment)
    }
}

