//
// ApiV1RunnersJobsJobUUIDErrorPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsJobUUIDErrorPostRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var runnerToken: String
    public var jobToken: String
    /** Why the runner failed to process this job */
    public var message: String

    public init(runnerToken: String, jobToken: String, message: String) {
        self.runnerToken = runnerToken
        self.jobToken = jobToken
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case runnerToken
        case jobToken
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(runnerToken, forKey: .runnerToken)
        try container.encode(jobToken, forKey: .jobToken)
        try container.encode(message, forKey: .message)
    }
}

