//
// ApiV1RunnersJobsJobUUIDAcceptPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersJobsJobUUIDAcceptPost200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var job: ApiV1RunnersJobsJobUUIDAcceptPost200ResponseJob?

    public init(job: ApiV1RunnersJobsJobUUIDAcceptPost200ResponseJob? = nil) {
        self.job = job
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case job
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(job, forKey: .job)
    }
}

