//
// ApiV1UsersMeNotificationsReadPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1UsersMeNotificationsReadPostRequest: Sendable, Codable, JSONEncodable, Hashable {

    /** ids of the notifications to mark as read */
    public var ids: [Int]

    public init(ids: [Int]) {
        self.ids = ids
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ids, forKey: .ids)
    }
}

