//
// ApiV1RunnersRegisterPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersRegisterPostRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var registrationToken: String
    public var name: String
    public var description: String?

    public init(registrationToken: String, name: String, description: String? = nil) {
        self.registrationToken = registrationToken
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case registrationToken
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(registrationToken, forKey: .registrationToken)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

