//
// ApiV1RunnersUnregisterPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1RunnersUnregisterPostRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var runnerToken: String

    public init(runnerToken: String) {
        self.runnerToken = runnerToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case runnerToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(runnerToken, forKey: .runnerToken)
    }
}

