//
// CommentThreadResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CommentThreadResponse: Sendable, Codable, JSONEncodable, Hashable {

    public static let dataRule = ArrayRule(minItems: nil, maxItems: 100, uniqueItems: false)
    /** Total threads (included deleted ones) on this video */
    public var total: Int?
    /** Total not-deleted threads (included deleted ones) on this video */
    public var totalNotDeletedComments: Int?
    public var data: [VideoComment]?

    public init(total: Int? = nil, totalNotDeletedComments: Int? = nil, data: [VideoComment]? = nil) {
        self.total = total
        self.totalNotDeletedComments = totalNotDeletedComments
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case totalNotDeletedComments
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(totalNotDeletedComments, forKey: .totalNotDeletedComments)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

