//
// ConfirmTwoFactorRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ConfirmTwoFactorRequestRequest: Sendable, Codable, JSONEncodable, Hashable {

    /** Token to identify the two factor request */
    public var requestToken: String
    /** OTP token generated by the app */
    public var otpToken: String

    public init(requestToken: String, otpToken: String) {
        self.requestToken = requestToken
        self.otpToken = otpToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestToken
        case otpToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestToken, forKey: .requestToken)
        try container.encode(otpToken, forKey: .otpToken)
    }
}

