//
// GenerateVideoCaptionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GenerateVideoCaptionRequest: Sendable, Codable, JSONEncodable, Hashable {

    public var forceTranscription: Bool? = false

    public init(forceTranscription: Bool? = false) {
        self.forceTranscription = forceTranscription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case forceTranscription
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(forceTranscription, forKey: .forceTranscription)
    }
}

