//
// GetLatestUserImport200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetLatestUserImport200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var state: GetLatestUserImport200ResponseState?
    public var createdAt: Date?

    public init(id: Int? = nil, state: GetLatestUserImport200ResponseState? = nil, createdAt: Date? = nil) {
        self.id = id
        self.state = state
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case state
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetLatestUserImport200Response: Identifiable {}
