//
// ImportVideosInChannelCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImportVideosInChannelCreate: Sendable, Codable, JSONEncodable, Hashable {

    public var externalChannelUrl: String
    /** If part of a channel sync process, specify its id to assign video imports to this channel synchronization */
    public var videoChannelSyncId: Int?

    public init(externalChannelUrl: String, videoChannelSyncId: Int? = nil) {
        self.externalChannelUrl = externalChannelUrl
        self.videoChannelSyncId = videoChannelSyncId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalChannelUrl
        case videoChannelSyncId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalChannelUrl, forKey: .externalChannelUrl)
        try container.encodeIfPresent(videoChannelSyncId, forKey: .videoChannelSyncId)
    }
}

