//
// LiveVideoReplaySettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveVideoReplaySettings: Sendable, Codable, JSONEncodable, Hashable {

    public var privacy: VideoPrivacySet?

    public init(privacy: VideoPrivacySet? = nil) {
        self.privacy = privacy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case privacy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(privacy, forKey: .privacy)
    }
}

