//
// NotificationType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Notification type. One of the following values:    - &#x60;1&#x60; NEW_VIDEO_FROM_SUBSCRIPTION    - &#x60;2&#x60; NEW_COMMENT_ON_MY_VIDEO    - &#x60;3&#x60; NEW_ABUSE_FOR_MODERATORS    - &#x60;4&#x60; BLACKLIST_ON_MY_VIDEO    - &#x60;5&#x60; UNBLACKLIST_ON_MY_VIDEO    - &#x60;6&#x60; MY_VIDEO_PUBLISHED    - &#x60;7&#x60; MY_VIDEO_IMPORT_SUCCESS    - &#x60;8&#x60; MY_VIDEO_IMPORT_ERROR    - &#x60;9&#x60; NEW_USER_REGISTRATION    - &#x60;10&#x60; NEW_FOLLOW    - &#x60;11&#x60; COMMENT_MENTION    - &#x60;12&#x60; VIDEO_AUTO_BLACKLIST_FOR_MODERATORS    - &#x60;13&#x60; NEW_INSTANCE_FOLLOWER    - &#x60;14&#x60; AUTO_INSTANCE_FOLLOWING    - &#x60;15&#x60; ABUSE_STATE_CHANGE    - &#x60;16&#x60; ABUSE_NEW_MESSAGE    - &#x60;17&#x60; NEW_PLUGIN_VERSION    - &#x60;18&#x60; NEW_PEERTUBE_VERSION    - &#x60;19&#x60; MY_VIDEO_STUDIO_EDITION_FINISHED    - &#x60;20&#x60; NEW_USER_REGISTRATION_REQUEST    - &#x60;21&#x60; NEW_LIVE_FROM_SUBSCRIPTION    - &#x60;22&#x60; MY_VIDEO_TRANSCRIPTION_GENERATED  */
public enum NotificationType: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case _6 = 6
    case _7 = 7
    case _8 = 8
    case _9 = 9
    case _10 = 10
    case _11 = 11
    case _12 = 12
    case _13 = 13
    case _14 = 14
    case _15 = 15
    case _16 = 16
    case _17 = 17
    case _18 = 18
    case _19 = 19
    case _20 = 20
    case _21 = 21
    case _22 = 22
}
