//
// OAuthClient.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OAuthClient: Sendable, Codable, JSONEncodable, Hashable {

    public static let clientIdRule = StringRule(minLength: 32, maxLength: 32, pattern: "/^[a-z0-9]$/")
    public static let clientSecretRule = StringRule(minLength: 32, maxLength: 32, pattern: "/^[a-zA-Z0-9]$/")
    public var clientId: String?
    public var clientSecret: String?

    public init(clientId: String? = nil, clientSecret: String? = nil) {
        self.clientId = clientId
        self.clientSecret = clientSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case clientSecret = "client_secret"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
    }
}

