//
// ReplaceVideoChaptersRequestChaptersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReplaceVideoChaptersRequestChaptersInner: Sendable, Codable, JSONEncodable, Hashable {

    public var title: String?
    public var timecode: Int?

    public init(title: String? = nil, timecode: Int? = nil) {
        self.title = title
        self.timecode = timecode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case timecode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(timecode, forKey: .timecode)
    }
}

