//
// RequestUserExportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestUserExportRequest: Sendable, Codable, JSONEncodable, Hashable {

    /** Whether to include video files in the archive */
    public var withVideoFiles: Bool?

    public init(withVideoFiles: Bool? = nil) {
        self.withVideoFiles = withVideoFiles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case withVideoFiles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(withVideoFiles, forKey: .withVideoFiles)
    }
}

