//
// RequestTwoFactorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestTwoFactorResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var otpRequest: RequestTwoFactorResponseOtpRequest?

    public init(otpRequest: RequestTwoFactorResponseOtpRequest? = nil) {
        self.otpRequest = otpRequest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case otpRequest
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(otpRequest, forKey: .otpRequest)
    }
}

