//
// RequestUserExport200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RequestUserExport200Response: Sendable, Codable, JSONEncodable, Hashable {

    public var export: RequestUserExport200ResponseExport?

    public init(export: RequestUserExport200ResponseExport? = nil) {
        self.export = export
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case export
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(export, forKey: .export)
    }
}

