//
// RunnerJobState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The runner job state:   - &#x60;1&#x60; Pending   - &#x60;2&#x60; Processing   - &#x60;3&#x60; Completed   - &#x60;4&#x60; Errored   - &#x60;5&#x60; Waiting for a parent job   - &#x60;6&#x60; Cancelled   - &#x60;7&#x60; Parent had an error   - &#x60;8&#x60; Parent has been cancelled  */
public enum RunnerJobState: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case _6 = 6
    case _7 = 7
    case _8 = 8
}
