//
// RunnerRegistrationToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RunnerRegistrationToken: Sendable, Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var registrationToken: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var registeredRunnersCount: Int?

    public init(id: Int? = nil, registrationToken: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, registeredRunnersCount: Int? = nil) {
        self.id = id
        self.registrationToken = registrationToken
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.registeredRunnersCount = registeredRunnersCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case registrationToken
        case createdAt
        case updatedAt
        case registeredRunnersCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(registrationToken, forKey: .registrationToken)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(registeredRunnersCount, forKey: .registeredRunnersCount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RunnerRegistrationToken: Identifiable {}
