//
// ServerConfigAvatar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAvatar: Sendable, Codable, JSONEncodable, Hashable {

    public var file: ServerConfigAvatarFile?
    public var extensions: [String]?

    public init(file: ServerConfigAvatarFile? = nil, extensions: [String]? = nil) {
        self.file = file
        self.extensions = extensions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
        case extensions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(extensions, forKey: .extensions)
    }
}

