//
// ServerConfigImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigImport: Sendable, Codable, JSONEncodable, Hashable {

    public var videos: ServerConfigImportVideos?
    public var videoChannelSynchronization: ServerConfigEmail?
    public var users: ServerConfigEmail?

    public init(videos: ServerConfigImportVideos? = nil, videoChannelSynchronization: ServerConfigEmail? = nil, users: ServerConfigEmail? = nil) {
        self.videos = videos
        self.videoChannelSynchronization = videoChannelSynchronization
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videos
        case videoChannelSynchronization
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videos, forKey: .videos)
        try container.encodeIfPresent(videoChannelSynchronization, forKey: .videoChannelSynchronization)
        try container.encodeIfPresent(users, forKey: .users)
    }
}

