//
// ServerConfigInstanceSocial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigInstanceSocial: Sendable, Codable, JSONEncodable, Hashable {

    public var externalLink: String?
    public var mastodonLink: String?
    public var blueskyLink: String?

    public init(externalLink: String? = nil, mastodonLink: String? = nil, blueskyLink: String? = nil) {
        self.externalLink = externalLink
        self.mastodonLink = mastodonLink
        self.blueskyLink = blueskyLink
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalLink
        case mastodonLink
        case blueskyLink
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(externalLink, forKey: .externalLink)
        try container.encodeIfPresent(mastodonLink, forKey: .mastodonLink)
        try container.encodeIfPresent(blueskyLink, forKey: .blueskyLink)
    }
}

