//
// ServerConfigVideoFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigVideoFile: Sendable, Codable, JSONEncodable, Hashable {

    public var extensions: [String]?

    public init(extensions: [String]? = nil) {
        self.extensions = extensions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case extensions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(extensions, forKey: .extensions)
    }
}

