//
// ServerConfigSignup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigSignup: Sendable, Codable, JSONEncodable, Hashable {

    public var allowed: Bool?
    public var allowedForCurrentIP: Bool?
    public var requiresEmailVerification: Bool?

    public init(allowed: Bool? = nil, allowedForCurrentIP: Bool? = nil, requiresEmailVerification: Bool? = nil) {
        self.allowed = allowed
        self.allowedForCurrentIP = allowedForCurrentIP
        self.requiresEmailVerification = requiresEmailVerification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowed
        case allowedForCurrentIP
        case requiresEmailVerification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowed, forKey: .allowed)
        try container.encodeIfPresent(allowedForCurrentIP, forKey: .allowedForCurrentIP)
        try container.encodeIfPresent(requiresEmailVerification, forKey: .requiresEmailVerification)
    }
}

