//
// ServerConfigAvatarFileSize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAvatarFileSize: Sendable, Codable, JSONEncodable, Hashable {

    public var max: Int?

    public init(max: Int? = nil) {
        self.max = max
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case max
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(max, forKey: .max)
    }
}

