//
// ServerConfigCustomFollowersInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomFollowersInstance: Sendable, Codable, JSONEncodable, Hashable {

    public var enabled: Bool?
    public var manualApproval: Bool?

    public init(enabled: Bool? = nil, manualApproval: Bool? = nil) {
        self.enabled = enabled
        self.manualApproval = manualApproval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case manualApproval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(manualApproval, forKey: .manualApproval)
    }
}

