//
// ServerConfigAbout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigAbout: Sendable, Codable, JSONEncodable, Hashable {

    public var instance: ServerConfigAboutInstance?

    public init(instance: ServerConfigAboutInstance? = nil) {
        self.instance = instance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(instance, forKey: .instance)
    }
}

