//
// ServerConfigTrending.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigTrending: Sendable, Codable, JSONEncodable, Hashable {

    public var videos: ServerConfigTrendingVideos?

    public init(videos: ServerConfigTrendingVideos? = nil) {
        self.videos = videos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videos, forKey: .videos)
    }
}

