//
// ServerConfigVideoCaptionFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigVideoCaptionFile: Sendable, Codable, JSONEncodable, Hashable {

    public var size: ServerConfigAvatarFileSize?
    public var extensions: [String]?

    public init(size: ServerConfigAvatarFileSize? = nil, extensions: [String]? = nil) {
        self.size = size
        self.extensions = extensions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case size
        case extensions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(extensions, forKey: .extensions)
    }
}

