//
// ServerConfigInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigInstance: Sendable, Codable, JSONEncodable, Hashable {

    public var name: String?
    public var shortDescription: String?
    public var defaultClientRoute: String?
    public var isNSFW: Bool?
    public var defaultNSFWPolicy: String?
    public var serverCountry: String?
    public var support: ServerConfigInstanceSupport?
    public var social: ServerConfigInstanceSocial?
    public var customizations: ServerConfigInstanceCustomizations?
    public var avatars: [ActorImage]?
    public var banners: [ActorImage]?

    public init(name: String? = nil, shortDescription: String? = nil, defaultClientRoute: String? = nil, isNSFW: Bool? = nil, defaultNSFWPolicy: String? = nil, serverCountry: String? = nil, support: ServerConfigInstanceSupport? = nil, social: ServerConfigInstanceSocial? = nil, customizations: ServerConfigInstanceCustomizations? = nil, avatars: [ActorImage]? = nil, banners: [ActorImage]? = nil) {
        self.name = name
        self.shortDescription = shortDescription
        self.defaultClientRoute = defaultClientRoute
        self.isNSFW = isNSFW
        self.defaultNSFWPolicy = defaultNSFWPolicy
        self.serverCountry = serverCountry
        self.support = support
        self.social = social
        self.customizations = customizations
        self.avatars = avatars
        self.banners = banners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case shortDescription
        case defaultClientRoute
        case isNSFW
        case defaultNSFWPolicy
        case serverCountry
        case support
        case social
        case customizations
        case avatars
        case banners
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(shortDescription, forKey: .shortDescription)
        try container.encodeIfPresent(defaultClientRoute, forKey: .defaultClientRoute)
        try container.encodeIfPresent(isNSFW, forKey: .isNSFW)
        try container.encodeIfPresent(defaultNSFWPolicy, forKey: .defaultNSFWPolicy)
        try container.encodeIfPresent(serverCountry, forKey: .serverCountry)
        try container.encodeIfPresent(support, forKey: .support)
        try container.encodeIfPresent(social, forKey: .social)
        try container.encodeIfPresent(customizations, forKey: .customizations)
        try container.encodeIfPresent(avatars, forKey: .avatars)
        try container.encodeIfPresent(banners, forKey: .banners)
    }
}

