//
// VideosForXMLInnerMediaThumbnail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideosForXMLInnerMediaThumbnail: Sendable, Codable, JSONEncodable, Hashable {

    public var url: String?
    public var height: Int?
    public var width: Int?

    public init(url: String? = nil, height: Int? = nil, width: Int? = nil) {
        self.url = url
        self.height = height
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case height
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

