//
// VideoUploadResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoUploadResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var video: VideoUploadResponseVideo?

    public init(video: VideoUploadResponseVideo? = nil) {
        self.video = video
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case video
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(video, forKey: .video)
    }
}

