//
// VideoStatsOverallCountriesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStatsOverallCountriesInner: Sendable, Codable, JSONEncodable, Hashable {

    public var isoCode: String?
    public var viewers: Double?

    public init(isoCode: String? = nil, viewers: Double? = nil) {
        self.isoCode = isoCode
        self.viewers = viewers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isoCode
        case viewers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isoCode, forKey: .isoCode)
        try container.encodeIfPresent(viewers, forKey: .viewers)
    }
}

