//
// VideoComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoComment: Sendable, Codable, JSONEncodable, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let textRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let threadIdRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let inReplyToCommentIdRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let videoIdRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalRepliesFromVideoAuthorRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalRepliesRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var url: String?
    /** Text of the comment */
    public var text: String?
    public var threadId: Int?
    public var inReplyToCommentId: Int?
    public var videoId: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var deletedAt: Date?
    public var isDeleted: Bool? = false
    public var heldForReview: Bool?
    public var totalRepliesFromVideoAuthor: Int?
    public var totalReplies: Int?
    public var account: Account?

    public init(id: Int? = nil, url: String? = nil, text: String? = nil, threadId: Int? = nil, inReplyToCommentId: Int? = nil, videoId: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, deletedAt: Date? = nil, isDeleted: Bool? = false, heldForReview: Bool? = nil, totalRepliesFromVideoAuthor: Int? = nil, totalReplies: Int? = nil, account: Account? = nil) {
        self.id = id
        self.url = url
        self.text = text
        self.threadId = threadId
        self.inReplyToCommentId = inReplyToCommentId
        self.videoId = videoId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.deletedAt = deletedAt
        self.isDeleted = isDeleted
        self.heldForReview = heldForReview
        self.totalRepliesFromVideoAuthor = totalRepliesFromVideoAuthor
        self.totalReplies = totalReplies
        self.account = account
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case text
        case threadId
        case inReplyToCommentId
        case videoId
        case createdAt
        case updatedAt
        case deletedAt
        case isDeleted
        case heldForReview
        case totalRepliesFromVideoAuthor
        case totalReplies
        case account
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(inReplyToCommentId, forKey: .inReplyToCommentId)
        try container.encodeIfPresent(videoId, forKey: .videoId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(heldForReview, forKey: .heldForReview)
        try container.encodeIfPresent(totalRepliesFromVideoAuthor, forKey: .totalRepliesFromVideoAuthor)
        try container.encodeIfPresent(totalReplies, forKey: .totalReplies)
        try container.encodeIfPresent(account, forKey: .account)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VideoComment: Identifiable {}
