//
// VideoResolutionConstant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** resolutions and their labels for the video */
public struct VideoResolutionConstant: Sendable, Codable, JSONEncodable, Hashable {

    /** Video resolution (`0`, `240`, `360`, `720`, `1080`, `1440` or `2160`)  `0` is used as a special value for stillimage videos dedicated to audio, a.k.a. audio-only videos.  */
    public var id: Int?
    public var label: String?

    public init(id: Int? = nil, label: String? = nil) {
        self.id = id
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VideoResolutionConstant: Identifiable {}
