//
// VideoTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoTokenResponse: Sendable, Codable, JSONEncodable, Hashable {

    public var files: VideoTokenResponseFiles?

    public init(files: VideoTokenResponseFiles? = nil) {
        self.files = files
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case files
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(files, forKey: .files)
    }
}

