//
// VideoPlaylistPrivacySet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Video playlist privacy policy (see [/video-playlists/privacies](#operation/getPlaylistPrivacyPolicies)) */
public enum VideoPlaylistPrivacySet: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
}
