//
// VideoPrivacySet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** privacy id of the video (see [/videos/privacies](#operation/getVideoPrivacyPolicies)) */
public enum VideoPrivacySet: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
}
