//
// VideoCaption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoCaption: Sendable, Codable, JSONEncodable, Hashable {

    public var language: VideoConstantStringLanguage?
    public var captionPath: String?

    public init(language: VideoConstantStringLanguage? = nil, captionPath: String? = nil) {
        self.language = language
        self.captionPath = captionPath
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case captionPath
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(captionPath, forKey: .captionPath)
    }
}

