//
// VODAudioMergeTranscoding1Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VODAudioMergeTranscoding1Input: Sendable, Codable, JSONEncodable, Hashable {

    public var audioFileUrl: String?
    public var previewFileUrl: String?

    public init(audioFileUrl: String? = nil, previewFileUrl: String? = nil) {
        self.audioFileUrl = audioFileUrl
        self.previewFileUrl = previewFileUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audioFileUrl
        case previewFileUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(audioFileUrl, forKey: .audioFileUrl)
        try container.encodeIfPresent(previewFileUrl, forKey: .previewFileUrl)
    }
}

