//
// RunnerJobsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RunnerJobsAPI {

    /**
     * enum for parameter sort
     */
    public enum Sort_apiV1RunnersJobsGet: String, Sendable, CaseIterable {
        case updatedat = "updatedAt"
        case createdat = "createdAt"
        case priority = "priority"
        case state = "state"
        case progress = "progress"
    }

    /**
     List jobs
     
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort runner jobs by criteria (optional)
     - parameter search: (query) Plain text search, applied to various parts of the model depending on endpoint (optional)
     - parameter stateOneOf: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiV1RunnersJobsGet200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsGet(start: Int? = nil, count: Int? = nil, sort: Sort_apiV1RunnersJobsGet? = nil, search: String? = nil, stateOneOf: [RunnerJobState]? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ApiV1RunnersJobsGet200Response {
        return try await apiV1RunnersJobsGetWithRequestBuilder(start: start, count: count, sort: sort, search: search, stateOneOf: stateOneOf, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List jobs
     - GET /api/v1/runners/jobs
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort runner jobs by criteria (optional)
     - parameter search: (query) Plain text search, applied to various parts of the model depending on endpoint (optional)
     - parameter stateOneOf: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiV1RunnersJobsGet200Response> 
     */
    open class func apiV1RunnersJobsGetWithRequestBuilder(start: Int? = nil, count: Int? = nil, sort: Sort_apiV1RunnersJobsGet? = nil, search: String? = nil, stateOneOf: [RunnerJobState]? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ApiV1RunnersJobsGet200Response> {
        let localVariablePath = "/api/v1/runners/jobs"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start": (wrappedValue: start?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "stateOneOf": (wrappedValue: stateOneOf?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1RunnersJobsGet200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Abort job
     
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDAbortPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDAbortPost(jobUUID: UUID, apiV1RunnersJobsJobUUIDAbortPostRequest: ApiV1RunnersJobsJobUUIDAbortPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDAbortPostWithRequestBuilder(jobUUID: jobUUID, apiV1RunnersJobsJobUUIDAbortPostRequest: apiV1RunnersJobsJobUUIDAbortPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Abort job
     - POST /api/v1/runners/jobs/{jobUUID}/abort
     - API used by PeerTube runners
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDAbortPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDAbortPostWithRequestBuilder(jobUUID: UUID, apiV1RunnersJobsJobUUIDAbortPostRequest: ApiV1RunnersJobsJobUUIDAbortPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/abort"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersJobsJobUUIDAbortPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Accept job
     
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiV1RunnersJobsJobUUIDAcceptPost200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDAcceptPost(jobUUID: UUID, apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ApiV1RunnersJobsJobUUIDAcceptPost200Response {
        return try await apiV1RunnersJobsJobUUIDAcceptPostWithRequestBuilder(jobUUID: jobUUID, apiV1RunnersUnregisterPostRequest: apiV1RunnersUnregisterPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Accept job
     - POST /api/v1/runners/jobs/{jobUUID}/accept
     - API used by PeerTube runners
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiV1RunnersJobsJobUUIDAcceptPost200Response> 
     */
    open class func apiV1RunnersJobsJobUUIDAcceptPostWithRequestBuilder(jobUUID: UUID, apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ApiV1RunnersJobsJobUUIDAcceptPost200Response> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/accept"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersUnregisterPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1RunnersJobsJobUUIDAcceptPost200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Cancel a job
     
     - parameter jobUUID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDCancelGet(jobUUID: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDCancelGetWithRequestBuilder(jobUUID: jobUUID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Cancel a job
     - GET /api/v1/runners/jobs/{jobUUID}/cancel
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter jobUUID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDCancelGetWithRequestBuilder(jobUUID: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/cancel"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a job
     
     - parameter jobUUID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDDelete(jobUUID: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDDeleteWithRequestBuilder(jobUUID: jobUUID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a job
     - DELETE /api/v1/runners/jobs/{jobUUID}
     - The endpoint will first cancel the job if needed, and then remove it from the database. Children jobs will also be removed
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter jobUUID: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDDeleteWithRequestBuilder(jobUUID: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Post job error
     
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDErrorPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDErrorPost(jobUUID: UUID, apiV1RunnersJobsJobUUIDErrorPostRequest: ApiV1RunnersJobsJobUUIDErrorPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDErrorPostWithRequestBuilder(jobUUID: jobUUID, apiV1RunnersJobsJobUUIDErrorPostRequest: apiV1RunnersJobsJobUUIDErrorPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Post job error
     - POST /api/v1/runners/jobs/{jobUUID}/error
     - API used by PeerTube runners
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDErrorPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDErrorPostWithRequestBuilder(jobUUID: UUID, apiV1RunnersJobsJobUUIDErrorPostRequest: ApiV1RunnersJobsJobUUIDErrorPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/error"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersJobsJobUUIDErrorPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Post job success
     
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDSuccessPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDSuccessPost(jobUUID: UUID, apiV1RunnersJobsJobUUIDSuccessPostRequest: ApiV1RunnersJobsJobUUIDSuccessPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDSuccessPostWithRequestBuilder(jobUUID: jobUUID, apiV1RunnersJobsJobUUIDSuccessPostRequest: apiV1RunnersJobsJobUUIDSuccessPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Post job success
     - POST /api/v1/runners/jobs/{jobUUID}/success
     - API used by PeerTube runners
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDSuccessPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDSuccessPostWithRequestBuilder(jobUUID: UUID, apiV1RunnersJobsJobUUIDSuccessPostRequest: ApiV1RunnersJobsJobUUIDSuccessPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/success"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersJobsJobUUIDSuccessPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update job
     
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDUpdatePostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsJobUUIDUpdatePost(jobUUID: UUID, apiV1RunnersJobsJobUUIDUpdatePostRequest: ApiV1RunnersJobsJobUUIDUpdatePostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1RunnersJobsJobUUIDUpdatePostWithRequestBuilder(jobUUID: jobUUID, apiV1RunnersJobsJobUUIDUpdatePostRequest: apiV1RunnersJobsJobUUIDUpdatePostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update job
     - POST /api/v1/runners/jobs/{jobUUID}/update
     - API used by PeerTube runners
     - parameter jobUUID: (path)  
     - parameter apiV1RunnersJobsJobUUIDUpdatePostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersJobsJobUUIDUpdatePostWithRequestBuilder(jobUUID: UUID, apiV1RunnersJobsJobUUIDUpdatePostRequest: ApiV1RunnersJobsJobUUIDUpdatePostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/jobs/{jobUUID}/update"
        let jobUUIDPreEscape = "\(APIHelper.mapValueToPathItem(jobUUID))"
        let jobUUIDPostEscape = jobUUIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobUUID}", with: jobUUIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersJobsJobUUIDUpdatePostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Request a new job
     
     - parameter apiV1RunnersJobsRequestPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiV1RunnersJobsRequestPost200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1RunnersJobsRequestPost(apiV1RunnersJobsRequestPostRequest: ApiV1RunnersJobsRequestPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ApiV1RunnersJobsRequestPost200Response {
        return try await apiV1RunnersJobsRequestPostWithRequestBuilder(apiV1RunnersJobsRequestPostRequest: apiV1RunnersJobsRequestPostRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request a new job
     - POST /api/v1/runners/jobs/request
     - API used by PeerTube runners
     - parameter apiV1RunnersJobsRequestPostRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiV1RunnersJobsRequestPost200Response> 
     */
    open class func apiV1RunnersJobsRequestPostWithRequestBuilder(apiV1RunnersJobsRequestPostRequest: ApiV1RunnersJobsRequestPostRequest? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ApiV1RunnersJobsRequestPost200Response> {
        let localVariablePath = "/api/v1/runners/jobs/request"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersJobsRequestPostRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1RunnersJobsRequestPost200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
